apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: project-rust
  description: A Rust-based microservice component
  annotations:
    github.com/project-slug: anubhavg-icpl/project-rust
    backstage.io/techdocs-ref: dir:.
  tags:
    - rust
    - backend
    - service
  labels:
    language: rust
    tier: backend
    lifecycle: production
spec:
  type: service
  lifecycle: production
  owner: guests
  system: backend-services
  dependsOn:
    - resource:default/database
  providesApis:
    - project-rust-api
  consumesApis:
    - auth-service-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: project-rust-api
  description: REST API for the Rust service
  tags:
    - rest
    - rust
    - backend
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: ./openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-rust-resources
  description: Collection of resources for the Rust service
spec:
  targets:
    - ./apis/api-definition.yaml
    - ./components/database.yaml
    - ./components/dependencies.yaml