apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: project-rust
  description: |
    A Rust-based microservice component that demonstrates basic web service functionality.
  links:
    - title: API Documentation
      url: https://github.com/anubhavg-icpl/project-rust/blob/master/docs/api.md
    - title: Development Guide
      url: https://github.com/anubhavg-icpl/project-rust/blob/master/docs/development.md
    - title: Operations Guide
      url: https://github.com/anubhavg-icpl/project-rust/blob/master/docs/operations.md
  annotations:
    github.com/project-slug: anubhavg-icpl/project-rust
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental