site_name: "Project Rust"
site_description: "Documentation for the Rust Service Component"

nav:
  - Home: index.md
  - API: api.md
  - Development: development.md
  - Operations: operations.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

repo_url: https://github.com/anubhavg-icpl/project-rust
edit_uri: edit/master/docs